In [12]:
#1 Створіть одновимірний масив (вектор) зі зменшувальною арифметичною послідовністю, де кожне наступне число менше попереднього на 4, 
#починаючи з 50, та виведіть його значення. 
vector1 = [x for x in range(50, -1, -4)]
print(vector1)

[50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10, 6, 2]


In [23]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями суми добутків кожного числа на його попереднє, 
#починаючи з 1, та виведіть його значення. 
matrix = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(3):
    for j in range(3):
        if j == 0:
            matrix[i][j] = i + 1
        else:
            matrix[i][j] = matrix[i][j - 1] * (i + 1)

# Виводимо матрицю
for row in matrix:
    print(row)

[1, 1, 1]
[2, 4, 8]
[3, 9, 27]


In [24]:
#3 Створіть масив розміром 9x9, заповніть його випадковими цілими числами в діапазоні від -100 до 100 та знайдіть мінімальний елемент. 
import numpy as np
matrix = np.random.randint(-100, 101, (9, 9))
min_element = np.min(matrix)
print("Матриця:")
print(matrix)
print("Мінімальний елемент:", min_element)

Матриця:
[[-98 -33  63  18  38  87  30  -3 -79]
 [  5 -67 -68  57 -24 -27 -39  25 -26]
 [ 27 -30 -94 -10 -99 -35 -80  87  51]
 [ 62 -20 -48  98 -40  27  32  90  -3]
 [-24  49  16 -33 -75 -54  73  53 -20]
 [ -5  97 -26  79   4  49 -43 -23 -92]
 [-23 -77  22   9  37  21  87   7  73]
 [-71 -34   3  19  16 -29  72 -83  46]
 [-62 -27  24 -36  28 -23 -20 -76  25]]
Мінімальний елемент: -99


In [44]:
#4 Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток елементів, що менше 0.2. 
import numpy as np
array = np.random.rand(6, 6)
array = np.round(array, 5)
print("Масив:")
print(array)
result = np.prod(array[array < 0.2])
print("Добуток елементів, менших за 0.2:", result)

Масив:
[[0.79911 0.52129 0.2353  0.99596 0.91942 0.97232]
 [0.7113  0.00174 0.75817 0.4916  0.94742 0.26853]
 [0.30971 0.91783 0.3258  0.68605 0.94209 0.63717]
 [0.60899 0.26043 0.66735 0.21315 0.76546 0.42925]
 [0.15741 0.98623 0.63845 0.71021 0.14511 0.67016]
 [0.94513 0.0742  0.19392 0.09883 0.56251 0.1366 ]]
Добуток елементів, менших за 0.2: 7.720490835524156e-09
Добуток елементів, менших за 0.2: 1e-08


In [45]:
#5 Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від 0 до 1 
#та виконайте на них поелементні операції додавання, віднімання та множення. 
import numpy as np
array1 = np.random.rand(4)
array2 = np.random.rand(4)
print("Перший масив:", array1)
print("Другий масив:", array2)
dodavannya_result = array1 + array2
print("Результат додавання:", dodavannya_result)
vidnimannya_result = array1 - array2
print("Результат віднімання:", vidnimannya_result)
mnozhennya_result = array1 * array2
print("Результат множення:", mnozhennya_result)

Перший масив: [0.73313392 0.52846835 0.26184649 0.50414293]
Другий масив: [0.0411962  0.47731914 0.6830528  0.8441241 ]
Результат додавання: [0.77433012 1.00578749 0.94489928 1.34826703]
Результат віднімання: [ 0.69193771  0.05114921 -0.42120631 -0.33998117]
Результат множення: [0.03020233 0.25224806 0.17885497 0.42555919]


In [47]:
#6 Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 
import numpy as np
vector1 = np.array([1.2, 2.4, 3.6, 4.8])
vector2 = np.array([0.5, 1.0, 1.5, 2.0])
scalar_dobutok = np.dot(vector1, vector2)
print("Скалярний добуток двох векторів:", scalar_dobutok)

Скалярний добуток двох векторів: 18.0


In [48]:
#7 Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою. 
import numpy as np
matrix1 = np.random.randint(1, 11, (2, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

# Виведення згенерованих матриць
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

# Перемноження матриць
result_matrix = np.dot(matrix1, matrix2)

# Виведення результату
print("Результат перемноження матриць:")
print(result_matrix)

Перша матриця:
[[ 6 10  4]
 [ 4  5  6]]
Друга матриця:
[[ 5  5  3]
 [ 6  9  3]
 [10  9  1]]
Результат перемноження матриць:
[[130 156  52]
 [110 119  33]]


In [50]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю. 
import numpy as np
matrix = np.random.randint(1, 9, (3, 3))
print("Початкова матриця:")
print(matrix)

# Знаходження оберненої матриці
inverse_matrix = np.linalg.inv(matrix)
print("Обернена матриця:")
print(inverse_matrix)

Початкова матриця:
[[7 1 8]
 [1 7 1]
 [7 3 6]]
Обернена матриця:
[[-0.41489362 -0.19148936  0.58510638]
 [-0.0106383   0.14893617 -0.0106383 ]
 [ 0.4893617   0.14893617 -0.5106383 ]]


In [51]:
#9 Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від 50 до 100 та транспонуйте її. 
import numpy as np
matrix = np.random.uniform(50, 100, (8, 8))
print("Початкова матриця:")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[77.6639751  78.21618752 95.68536932 78.48204128 66.34710689 78.59611958
  95.45914686 52.76832915]
 [88.96613583 84.20895856 56.82937467 62.94615022 68.70334991 81.23483366
  93.49126758 98.85699465]
 [56.44004372 67.28689306 75.27237967 52.60661857 99.02283471 68.32245058
  66.47351179 80.84980051]
 [79.54237535 59.40060254 58.72274027 75.52299177 79.40119772 52.82876508
  95.11684936 66.54893642]
 [52.19688302 69.86371881 91.44834683 74.13891777 86.77337362 87.92289273
  87.52526779 51.07203035]
 [99.59211822 79.53883192 99.181283   81.8399266  82.15893003 87.92954512
  88.29267289 68.2438942 ]
 [94.09695593 95.81203503 76.58934869 76.31381869 54.65820138 97.90798687
  98.9429199  63.7571899 ]
 [78.27596336 51.51838941 72.84445678 82.04172948 90.16387715 78.93153725
  85.49358044 54.35433645]]

Транспонована матриця:
[[77.6639751  88.96613583 56.44004372 79.54237535 52.19688302 99.59211822
  94.09695593 78.27596336]
 [78.21618752 84.20895856 67.28689306 59.400602

In [53]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, 
#а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму додатних елементів отриманого вектору. 
import numpy as np
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, 4)
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Cумa додатних елементів вектора
positive_elements = vector[vector > 0]
sum_positive_elements = np.sum(positive_elements)
print("Сума додатних елементів вектора:", sum_positive_elements)

Матриця:
[[0.24260053 0.26859939 0.94113109 0.05273915]
 [0.65342747 0.14775887 0.16274331 0.10808184]
 [0.10961706 0.49985113 0.48174503 0.78137911]]
Вектор:
[9 6 5 6]
Сума додатних елементів вектора: 26


In [55]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, 
#а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які більше середнього значення матриці. 
import numpy as np
matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.rand(3)
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

# Середнього значення матриці
mean_matrix = np.mean(matrix)

# Сума елементів матриці, які більше середнього значення
sum_above_mean = np.sum(matrix[matrix > mean_matrix])

# Середнє значення та сума елементів, які більше середнього значення
print("Середнє значення матриці:", mean_matrix)
print("Сума елементів матриці, більших за середнє значення:", sum_above_mean)

Матриця:
[[9 5 2]
 [2 8 2]]
Вектор:
[0.31900037 0.25007652 0.89749095]
Середнє значення матриці: 4.666666666666667
Сума елементів матриці, більших за середнє значення: 22


In [56]:
#12 Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
#знайдіть відношення всіх елементів першої матриці до відповідних елементів другої матриці (поелементне ділення). 
import numpy as np
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

# Пелементне ділення
result_matrix = matrix1 / matrix2
print("Поелементне ділення : ")
print(result_matrix)

Перша матриця:
[[ 5  3  1  9  2]
 [ 3  6  9  4  3]
 [10 10  4  4  3]
 [10  9  2  3  9]
 [ 8  5  9  6  7]]
Друга матриця:
[[ 2  5  5  7  8]
 [ 4  5  9 10  8]
 [ 9  1  9 10  2]
 [ 9  6  1  3  9]
 [ 6  2  5  3  5]]
Поелементне ділення : 
[[ 2.5         0.6         0.2         1.28571429  0.25      ]
 [ 0.75        1.2         1.          0.4         0.375     ]
 [ 1.11111111 10.          0.44444444  0.4         1.5       ]
 [ 1.11111111  1.5         2.          1.          1.        ]
 [ 1.33333333  2.5         1.8         2.          1.4       ]]


In [57]:
#13 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та знайдіть різницю їх елементів. 
import numpy as np
matrix1 = np.random.randint(-10, 11, (4, 4))
matrix2 = np.random.randint(-10, 11, (4, 4))
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
result_matrix = matrix1 - matrix2
print("Результат (різниця елементів матриць):")
print(result_matrix)

Матриця 1:
[[  3   7   2   4]
 [ -3   4 -10   5]
 [ -6   9   0   5]
 [ -7  -6 -10   3]]
Матриця 2:
[[-4 -8  5  0]
 [ 2 -9  3  4]
 [-1 -7  7 10]
 [-4  3 10 -2]]
Результат (різниця елементів матриць):
[[  7  15  -3   4]
 [ -5  13 -13   1]
 [ -5  16  -7  -5]
 [ -3  -9 -20   5]]


In [58]:
#14 Створіть матрицю розміром 10x10, заповніть її випадковими цілими числами в діапазоні від 1 до 100 
#та знайдіть суму елементів матриці, які менше за їх середнє арифметичне значення. 
import numpy as np
matrix = np.random.randint(1, 101, (10, 10))
print("Матриця:")
print(matrix)
mean_value = np.mean(matrix)

# Сума елементів, які менше за середнє арифметичне значення
sum_below_mean = np.sum(matrix[matrix < mean_value])

# Середнє арифметичне значення та сума елементів, які менше за нього
print("Середнє арифметичне значення матриці:", mean_value)
print("Сума елементів, які менше за середнє значення:", sum_below_mean)

Матриця:
[[ 7 36 72  1 57 69 98 97 30 64]
 [ 3 20 32 37 94 86 57 57 35 83]
 [29 40  3 54 36  1  8 88 26 28]
 [78  5 29 17 98 55 29 31  8 32]
 [19 72 19 89 42 17 53 29 24 71]
 [37 62 89 60 28 46 67 53 32 22]
 [68 71 14  4 68 55 77 31 60 60]
 [24 50 60 78 90 39 23 45 95 75]
 [61 63  5 68  2 43 26 95 80 28]
 [30 58 79 95 96 53 99 49 65 16]]
Середнє арифметичне значення матриці: 48.59
Сума елементів, які менше за середнє значення: 1168


In [59]:
#15 Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та 
#знайдіть вектор-стовпчик, що містить середнє гармонічне значення елементів кожного рядка матриці. 
import numpy as np
matrix = np.random.uniform(-2, 2, (6, 6))
print("Матриця:")
print(matrix)
print ("Cереднє гармонічне значення елементів кожного рядка матриці")
harmonic_means = np.apply_along_axis(lambda x: len(x) / np.sum(1.0 / x), axis=1, arr=matrix)
print ("Cереднє гармонічне значення елементів кожного рядка матриці")
harmonic_means = harmonic_means[:, np.newaxis]
print("\nВектор-стовпчик з середніми гармонічними значеннями:")
print(harmonic_means)

Матриця:
[[ 0.28012862  1.18238449  1.03949447  1.93977284  0.11127041 -1.89108301]
 [-1.65441274  1.34506891  0.54243133  1.55669788  1.44191094  0.89183805]
 [-1.71473811  1.31426839  1.30775037 -0.01850714 -1.86463966 -0.79063202]
 [ 1.5806079  -0.95919627  1.64074641 -0.67002892  1.72069694  1.90745311]
 [ 1.76278026  0.9204312  -1.36302466 -0.23383323 -0.10908597  0.55507539]
 [ 1.56807159  1.51094215  1.45640534 -1.1674846  -0.60360425  1.49071261]]
Cереднє гармонічне значення елементів кожного рядка матриці
Cереднє гармонічне значення елементів кожного рядка матриці

Вектор-стовпчик з середніми гармонічними значеннями:
[[  0.4180781 ]
 [  1.35142656]
 [ -0.10930566]
 [-32.00912375]
 [ -0.55959675]
 [ 41.73917413]]


Висновок: на практичному занятті 1 я грунтовніше засвоїла матеріали з курсу лінійної алгебри (вектори, матриці, транспоновані, обернені матриці, множення матриць, знаходження середнього гармонічного значення елементів кожного рядка матриці тощо). Також, використала здобуті раніше навички у програмуванні на мові Python.